### ISSUE TITLE
노드 패키지 설정

### ISSUE THREAD

**Issue by codeisneverodd** [ConnecTo-FrontEnd/DDD#21]
아래와 같은 패키지를 설치하고 환경설정을 합니다.
## 패키지
- live-server
- npm-run-all
- sass
- prettier

## 환경설정
- .prettierrc.json
[레퍼런스](https://prettier.io/docs/en/install.html)
[에어비엔비 스타일 prettier](https://techwell.wooritech.com/docs/tools/prettier/prettier-eslint-airbnb/)
prettier 설정  및 커밋전에 prettier 돌아가도록 설정
```
{
  printWidth: 80, // 한 줄 최대 문자 수
  tabWidth: 2, // 들여쓰기 시, 탭 너비
  useTabs: false, // 스페이스 대신 탭 사용
  semi: true, // 문장 끝 세미콜론 사용
  singleQuote: false, // 작은 따옴표 사용
  trailingComma: 'all', // 꼬리 콤마 사용
  bracketSpacing: true, // 중괄호 내에 공백 사용
  arrowParens: 'avoid', // 화살표 함수 단일 인자 시, 괄호 생략
  proseWrap: 'never', // 마크다운 포매팅 제외
  endOfLine: 'auto', // 개행문자 유지 (혼합일 경우, 첫 줄 개행문자로 통일)
};
```
- .prettierignore
[레퍼런스](https://prettier.io/docs/en/install.html)
prettier 가 포맷팅 하지 않아도 될 파일들
```
/node_modules
각종 환경설정 파일
```
- .gitignore
[자동생성 사이트](https://www.toptal.com/developers/gitignore)
```
vscode, webstorm, window, mac 환경설정 파일 및
/node_modules
*.css 
*.css.map
```
- .live-server.json
[레퍼런스](https://www.npmjs.com/package/live-server)
```
{
	port: 8938, // 포트 넘버
	root: "/", //향후 public 폴더가 생기면 public
	open: true, // 실행시 브라우저 열림
	ignore: 'styles', // 무시할 경로
	file: "index.html", // 404 에러 시 올 페이지
}
```
- package.json
```
"start": "run-p watch serve",
"sass": "sass index.scss:index.css",
"watch": "npm run sass -- --watch",
"serve" : "live-server",
```

더 필요하거나 이상한 부분이 있다면 이곳에 답글로 남겨주세용

**Comment by codeisneverodd** [comment]
한 번에 다 하면 혼선이 있을 것으로 예상되어 배포를 위한 빌드 상황은 고려하지 않고, 로컬 개발 환경만 고려하였습니다.

**Comment by dikum98** [comment]
확인했습니다~!! bb

**Comment by jiseung-kang** [comment]
1. Nit..  `package.json`의 `"sass"` 값에 불필요한 공백 하나가 포함되어 있어요!

2. `singleQuote: true` 옵션에 일반적으로 동의하는데, 우리의 프로젝트는 `HTML`과 `CSS` 파일이 주가 되기 때문에 예외적으로 `doubleQuote`가 적용되는 부분들을 독자의 입장에서 조금 더 고려해야하지 않을까? 조심스럽게 의견 남겨봅니다! (**생각만 해보고, 그냥 넘어가도 좋습니다!**)

[구글 스타일 가이드](https://google.github.io/styleguide/htmlcssguide.html)에 따르면 

HTML 속성 값에는 큰 따옴표("") 사용을 권장하고 있고, 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/58802599/182273487-6ae62fec-c9a3-440c-acff-dab947de2a73.png">

CSS에서는 또 다르더라구요.. (복잡)
<img width="940" alt="image" src="https://user-images.githubusercontent.com/58802599/182273462-fda78f47-f8c3-4075-9f3f-d50ac1baae33.png">

> 우리끼리의 **일관성**과 사용자 입장에서의 **보편성**을 모두 얻고 싶은데 좋은 의견 있을까요?

**Comment by GuRaBang** [comment]
"sass": "sass  index.scss:index.css"
파일 단위로 설정하니까 index.scss에 포함되어 있다고 해도 index.scss파일 내부에 변화가 없으면 index.css에 반영이 안되는거 같아요...

**Comment by codeisneverodd** [comment]
@jiseung-kang
1. 불필요한 공백 제거 하겠습니다!
2. 좋은 의견이네요! 개발자끼리의 일관성을 지키고, 사실 사용자는 코드를 보지 않지만 저희의 사용자는 개발자이고 코드를 보기 때문에 좋은 고민인 것 같아요! 구글 스타일 가이드에 따라 작성하면 좋지만 prettier 설정을 언어별로 해주기 어려운 것 같아요! 우선 큰 따옴표 ("")로 설정하고, 향후 설정법을 찾는다면 언어별로 적절하게 지정해주는 것은 어떤가요!

**Comment by codeisneverodd** [comment]
@GuRaBang 질문을 제대로 이해하지 못했어요!
index.scss 를 수정해야 index.css가 변경되는 것이고, 공용 폴더에 있는 내용들은 수정될 일이 없는데 어떤 것을 말씀해주시는 것 일까요?

**Comment by GuRaBang** [comment]
아닙니다~ 제가 잘 못 이해했습니다... 해결!!

**Comment by codeisneverodd** [comment]
커밋 전에 prettier가 돌려지도록 하는 설정을 추가하였습니다!
[레퍼런스](https://prettier.io/docs/en/install.html)
추가한 패키지
- husky
- lint-staged
```
//package.json
"lint-staged": {
    "**/*": "prettier --write --ignore-unknown"
  }
```

**Comment by codeisneverodd** [comment]
#22 를 반영하여
htmlhint를 설치하고, 아래와 같이 스크립트를 추가하였습니다.
```
"check": "echo \"1. htmlhint 검사를 시행합니다.\" && npx htmlhint \"**/*.html\" && echo \"2. prettier 검사를 시행합니다.\" && npx prettier --check . ",
```
`npm run check` 를 시행하면 다음과 같이 표시됩니다.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/54318460/182294840-8cf32f33-de97-47fa-b7b8-7ff4000e4ebc.png">
